// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fast_1D_upgma_grouping_cpp
IntegerVector fast_1D_upgma_grouping_cpp(NumericVector x, double maxDiff);
RcppExport SEXP _carpeDIAMS_fast_1D_upgma_grouping_cpp(SEXP xSEXP, SEXP maxDiffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type maxDiff(maxDiffSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_1D_upgma_grouping_cpp(x, maxDiff));
    return rcpp_result_gen;
END_RCPP
}
// fast_1D_iaac_grouping_cpp
IntegerVector fast_1D_iaac_grouping_cpp(NumericVector mz, NumericVector intensity, double k, double p0, double Isat);
RcppExport SEXP _carpeDIAMS_fast_1D_iaac_grouping_cpp(SEXP mzSEXP, SEXP intensitySEXP, SEXP kSEXP, SEXP p0SEXP, SEXP IsatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type mz(mzSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intensity(intensitySEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type p0(p0SEXP);
    Rcpp::traits::input_parameter< double >::type Isat(IsatSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_1D_iaac_grouping_cpp(mz, intensity, k, p0, Isat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_carpeDIAMS_fast_1D_upgma_grouping_cpp", (DL_FUNC) &_carpeDIAMS_fast_1D_upgma_grouping_cpp, 2},
    {"_carpeDIAMS_fast_1D_iaac_grouping_cpp", (DL_FUNC) &_carpeDIAMS_fast_1D_iaac_grouping_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_carpeDIAMS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
