# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast 1D UPGMA grouping
#' @param mz numeric vector
#' @param maxDiff numeric scalar
#' @return integer vector of group ids
#' @export
fast_1D_upgma_grouping_cpp <- function(x, maxDiff) {
    .Call(`_carpeDIAMS_fast_1D_upgma_grouping_cpp`, x, maxDiff)
}

#' Fast 1D intensity-adaptive grouping (IAAC), O(n log n)
#' @param mz numeric vector of m/z values
#' @param intensity numeric vector (same length as mz)
#' @param k z-threshold; a group is kept iff every internal merge is <= k sigma
#' @param p0 floor mass accuracy in ppm (high-intensity limit / systematic floor)
#' @param Isat intensity at which the per-point precision plateaus at p0
#' @return integer vector of group ids (length(mz)), 1-indexed by min original position
#' @export
fast_1D_iaac_grouping_cpp <- function(mz, intensity, k, p0 = 5.0, Isat = 5e4) {
    .Call(`_carpeDIAMS_fast_1D_iaac_grouping_cpp`, mz, intensity, k, p0, Isat)
}

